/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include<FreeRTOS.h>
#include<FreeRTOSConfig.h>
#include<task.h>
#include<led.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef struct led{
	uint16_t pin;
	uint32_t delay;
}led_t;

void vLedTask(void *pvParam)
{
	led_t *param = (led_t *)pvParam;

	portTickType pxPreviousWakeupTime = xTaskGetTickCount();

	while(1)
	{
		led_toggle(param->pin);
		vTaskDelayUntil(&pxPreviousWakeupTime, param->delay / portTICK_RATE_MS);
	}

	vTaskDelete(NULL);
}

int main(void)
{
	led_t led1 = {LED_BLUE, 1000};
	led_t led2 = {LED_GREEN, 2000};
	led_t led3 = {LED_ORANGE, 3000};
	led_t led4 = {LED_RED, 4000};

	xTaskCreate(vLedTask, "Led1", configMINIMAL_STACK_SIZE, &led1, 4, NULL);
	xTaskCreate(vLedTask, "Led2", configMINIMAL_STACK_SIZE, &led2, 4, NULL);
	xTaskCreate(vLedTask, "Led3", configMINIMAL_STACK_SIZE, &led3, 4, NULL);
	xTaskCreate(vLedTask, "Led4", configMINIMAL_STACK_SIZE, &led4, 4, NULL);

	vTaskStartScheduler();

	while(1);
}

